// Regenerates js/lovenotes.js from a local, gitignored notes.private.txt.
//
//   node generate_notes.mjs
//
// notes.private.txt = 11 notes, one per trip day, separated by lines that
// contain only "---". The notes are base64-encoded (atob at runtime) purely so
// a curious glance at the source doesn't spoil them — this is not security.
//
// If notes.private.txt is absent, the placeholder DEFAULT_NOTES below are used,
// so the app always ships with working notes. Tanner: drop in your real 11 and
// re-run before Aug 1 (see EXECUTION_PLAN Appendix C / Phase 5 content lock).
import { readFileSync, writeFileSync, existsSync } from "node:fs";

// Placeholder notes — plain, warm, specific to each day, each ending "— T".
// These read fine on their own if Tanner never swaps them.
const DEFAULT_NOTES = [
  /* 1  Seattle arrival */
  "We made it. First morning of the rest of it, in a brand-new city with nothing we can't change. I just want to watch you take it all in. — T",
  /* 2  drive to Forks (Twilight) */
  "Long drive today. You, me, a playlist, and every dumb vampire joke I've been saving up. I'd take the scenic route with you every single time. — T",
  /* 3  rainforest morning */
  "Rain on the moss, coffee going cold, you laughing at me for knowing the Forks map by heart. This right here is the good stuff. — T",
  /* 4  boarding the ship */
  "A whole week on a boat with nowhere to be but next to you. I've been quietly looking forward to this since the day I met you. — T",
  /* 5  at sea */
  "A full day and nothing to do but find you a good chair and a better view. Let's waste it beautifully. — T",
  /* 6  Juneau whales */
  "Whales today. But honestly, I'll be watching your face the second you see them. That's the part I actually paid for. — T",
  /* 7  Skagway rail */
  "Up the mountain on an old train, you by the window. Nap on my shoulder if you want to. I've got us. — T",
  /* 8  Glacier Bay (cold) */
  "Today is the cold one. My whole job today is your hands. — T",
  /* 9  Ketchikan free day */
  "No schedule today. Just a little rainy town and you. Let's get lost on the boardwalk and eat too much salmon. — T",
  /* 10 Victoria night */
  "Last port. Lights on the water, one more pub, a country that isn't ours. I'm already not ready for this to end. — T",
  /* 11 home */
  "Flying home married. Same two people who left, except now it's official — and I've got the whole rest of it with you. — T"
];

const FILE = "notes.private.txt";
let notes;
if (existsSync(FILE)) {
  notes = readFileSync(FILE, "utf8")
    .split(/^\s*---\s*$/m)
    .map(s => s.trim())
    .filter(Boolean);
  console.log(`Read ${notes.length} note(s) from ${FILE}.`);
} else {
  notes = DEFAULT_NOTES;
  console.log(`No ${FILE} found — using ${notes.length} placeholder notes.`);
}

if (notes.length !== 11) {
  console.error(`Expected 11 notes, got ${notes.length}. Aborting.`);
  process.exit(1);
}

const usingPlaceholders = !existsSync(FILE);
const entries = notes
  .map((text, i) => `  ${i + 1}: "${Buffer.from(text, "utf8").toString("base64")}"`)
  .join(",\n");

const todo = usingPlaceholders
  ? "\n// TODO: Tanner, replace these with your real notes via notes.private.txt before Aug 1.\n"
  : "\n";

const out = `// AUTO-GENERATED by generate_notes.mjs — do not edit by hand.
// One love note per trip day (1–11), base64 so a glance at source won't spoil it.
// Decode at runtime with atob(); see renderLoveNotes() in app.js.${todo}const LOVE_NOTES = {
${entries}
};
`;

writeFileSync("js/lovenotes.js", out);
console.log("Wrote js/lovenotes.js" + (usingPlaceholders ? " (placeholders)." : "."));
