// Bump CACHE_NAME on ANY app change — fetches are cache-first, so installed copies
// only pick up updates when a new SW version installs and re-caches everything.
const CACHE_NAME = "honeymoon-pwa-v8";
const TILE_CACHE = "honeymoon-tiles-v1";

const CORE_ASSETS = [
  "./",
  "index.html",
  "manifest.json",
  "css/styles.css",
  "js/data.js",
  "js/store.js",
  "js/lovenotes.js",
  "js/checklist.js",
  "js/app.js",
  "vendor/leaflet/leaflet.js",
  "vendor/leaflet/leaflet.css",
  "vendor/leaflet/images/marker-icon.png",
  "vendor/leaflet/images/marker-icon-2x.png",
  "vendor/leaflet/images/marker-shadow.png",
  "fonts/playfair_variable.ttf",
  "fonts/playfair_variable_italic.ttf",
  "fonts/great_vibes.woff2",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/apple-touch-icon-180.png",
  "icons/apple-touch-icon-167.png",
  "icons/apple-touch-icon-152.png",
  "icons/favicon-32.png",
  "icons/favicon-16.png",
  "images/day1_seattle.jpg",
  "images/day2_lapush.jpg",
  "images/day3_rialto.jpg",
  "images/day4_cruiseship.jpg",
  "images/day5_insidepassage.jpg",
  "images/day6_juneauwhale.jpg",
  "images/day7_whitepass.jpg",
  "images/day8_glacierbay.jpg",
  "images/day9_ketchikan.jpg",
  "images/day10_victoria.jpg",
  "images/day11_airplane.jpg"
];

self.addEventListener("install", event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    // cache:"reload" bypasses the browser HTTP cache — without it, an update
    // deployed within GitHub Pages' max-age window can bake stale files into
    // the new cache version permanently (cache-first never rechecks).
    const fresh = u => new Request(u, { cache: "reload" });
    await cache.addAll(CORE_ASSETS.map(fresh));
    // Calendar event files (generated by generate_ics.mjs) — cached so the
    // "add to calendar" buttons keep working offline at sea. Best-effort: a
    // failure here must never block the app itself from installing.
    try {
      const res = await fetch(fresh("calendar/manifest.json"));
      await cache.put("calendar/manifest.json", res.clone());
      const files = await res.json();
      await cache.addAll(files.map(f => fresh("calendar/" + f)));
    } catch (e) { /* offline first install or missing manifest — fine */ }
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE_NAME && k !== TILE_CACHE).map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", event => {
  const url = new URL(event.request.url);

  // Map tiles: cache-first, cached indefinitely once viewed (for offline days at sea/rainforest)
  if (url.hostname.endsWith("tile.openstreetmap.org")) {
    event.respondWith(
      caches.open(TILE_CACHE).then(cache =>
        cache.match(event.request).then(cached => cached || fetch(event.request).then(res => {
          cache.put(event.request, res.clone());
          return res;
        }).catch(() => cached))
      )
    );
    return;
  }

  // Same-origin app assets: cache-first, falling back to network
  if (url.origin === location.origin) {
    event.respondWith(
      caches.match(event.request).then(cached => cached || fetch(event.request))
    );
  }
});
